### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by crisgarner** [AffogatoNetwork/v2#2]
- [x] NFT en lotes
- [x] Subdominios de cooperativas
- [x] Enviar correos a cooperativas
- [ ] Login solo coops 
- [x] Logos de coops
- [ ] Mandar la coop al api para que pueda identificar que NFT tiene que llevar
- [x] Subir NFTs a IPFS
- [x] Poner mensaje en lotes de cafe si no tiene lotes (actualmente se queda trabado en cargando)
- [x] Logo de Home redireccione al home
- [x] BD de info de productor
- [ ] Fotos en perfil de productor
- [x] Mostrar data de productor / productores en lote
- [x] Mostrar data de perfil de taza
