### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by bobbylicious** [AffogatoNetwork/v2#3]
- [ ] BD de info de productor
- [x] Escoger campos para la base de datos (Excel/JSON DEFINITIVO)
- [x] Matchear el NFT con el lote
- [ ] Optimizar el cargado de los lotes
- [x] Cambiar nombre de "Cooperativa" a "Empresa"
- [ ] Agregar filtros a la lista de lotes
- [ ] Mostrar data de productor / productores en lote (DINAMICO)
- [x] Acceso de COMPRADOR (hacer link y pop up/texto para accesar)
- [ ] Fotos de fincas
- [ ] Cambios de arte/texto en lotes (JOHN)

CHECKLIST DE CAPACITACION:
- [x] Login solo cooperativas
- [ ] Enviar correos a cooperativas
- [ ] Crear cuentas de cooperativa
- [ ] No mostrar creación de lotes en perfil de productor
- [ ] Visualizar lotes como productor
