### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by bobbylicious** [AffogatoNetwork/v2#4]
- [ ]  CAMBIAR "ID de Productor" por "Código de Empresa"
![Agregar PRODUCTOR_2](https://user-images.githubusercontent.com/6061168/182942491-973f9446-297f-44a4-bbdc-db0c3c812b99.png)

- [ ] CAMBIAR "Áreas Productivas" por "Áreas Productivas (en hectáreas)"
<img width="1552" alt="Agregar EMPRESA_2" src="https://user-images.githubusercontent.com/6061168/182946807-bc48d161-b844-4641-97a4-732bd9c5423a.png">

- [ ] CAMBIAR "ID" por "Código"
<img width="1552" alt="Web PRODUCTORES_1" src="https://user-images.githubusercontent.com/6061168/182946075-b16faeb1-c87d-4a53-8d91-f9bb5695b78f.png">

- [ ] AGREGAR función de BÚSQUEDA DINÁMICA por nombre, ID, género, ubicación, etc.
<img width="1552" alt="Web PRODUCTORES_2" src="https://user-images.githubusercontent.com/6061168/182945424-5443fa55-77d8-4518-ba32-8188f7d5897f.png">

- [ ] CAMBIAR el orden de las columnas (Código > Nombre > Género > Ubicación > Dirección de Cuenta > Biografía)
<img width="1552" alt="Web PRODUCTORES_2" src="https://user-images.githubusercontent.com/6061168/182945424-5443fa55-77d8-4518-ba32-8188f7d5897f.png">

- [ ] AGREGAR función de BÚSQUEDA DINÁMICA por finca, altura, proceso, etc.
<img width="1552" alt="Web HOME_2" src="https://user-images.githubusercontent.com/6061168/182947342-78d8c334-af52-4031-873c-8a4f0218b6da.png">
